"""update models

Revision ID: efcfb9ce3449
Revises: b8e9a387b7bf
Create Date: 2025-05-21 15:29:22.866573

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efcfb9ce3449"
down_revision: Union[str, None] = "b8e9a387b7bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books",
        "borrowed_date",
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(),
        existing_nullable=False,
        postgresql_using="borrowed_date::timestamp",
    )
    op.alter_column(
        "borrowed_books",
        "return_date",
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(),
        existing_nullable=True,
        postgresql_using="borrowed_date::timestamp",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "borrowed_books",
        "return_date",
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "borrowed_books",
        "borrowed_date",
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
